/**
 * DischargeSummaryPanel
 *
 * AI-generated discharge summary for completed (or in-progress) admissions.
 * Output is suitable for PhilHealth/HMO submission and patient copy.
 */
import React, { useState } from 'react';
import {
  Card, Button, Typography, Space, Alert, Spin, Tag, Divider,
  Descriptions, List, message, Tooltip
} from 'antd';
import {
  MedicineBoxOutlined, RobotOutlined, ReloadOutlined, CopyOutlined,
  PrinterOutlined, ExclamationCircleOutlined
} from '@ant-design/icons';
import { aiService } from '../../services/aiService';

const { Text, Paragraph, Title } = Typography;

interface DischargeSummary {
  chiefComplaint:          string;
  admissionDiagnosis:      string;
  hospitalCourse:          string;
  proceduresPerformed:     string[];
  dischargeDiagnosis:      string;
  conditionAtDischarge:    string;
  dischargeMedications:    string;
  activityRestrictions:    string;
  dietaryInstructions:     string;
  followUpInstructions:    string;
  returnPrecautions:       string[];
  philhealthNote:          string;
  fullText:                string;
  generatedAt:             string;
  disclaimer:              string;
}

interface Props {
  patientId:    string;
  admissionId:  string;
  patientName?: string;
  onGenerated?: (summary: DischargeSummary) => void;
}

const SectionBlock: React.FC<{ label: string; content: string; mono?: boolean }> = ({
  label, content, mono = false,
}) => (
  <div style={{ marginBottom: 16 }}>
    <Text strong style={{ fontSize: 13, display: 'block', marginBottom: 4 }}>
      {label}
    </Text>
    <Paragraph
      style={{
        background: '#fafafa',
        border: '1px solid #e8e8e8',
        borderRadius: 6,
        padding: '10px 14px',
        marginBottom: 0,
        fontSize: 13,
        whiteSpace: 'pre-wrap',
        fontFamily: mono ? 'monospace' : 'inherit',
      }}
    >
      {content || <Text type="secondary" italic>Not documented</Text>}
    </Paragraph>
  </div>
);

const DischargeSummaryPanel: React.FC<Props> = ({
  patientId, admissionId, patientName, onGenerated,
}) => {
  const [loading,  setLoading]  = useState(false);
  const [summary,  setSummary]  = useState<DischargeSummary | null>(null);
  const [error,    setError]    = useState<string | null>(null);
  const [view,     setView]     = useState<'structured' | 'full'>('structured');

  const generate = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await aiService.generateDischargeSummary(patientId, admissionId);
      setSummary(data);
      onGenerated?.(data);
    } catch (err: any) {
      const msg = err?.response?.data?.message ?? 'Failed to generate discharge summary';
      setError(msg);
      message.error(msg);
    } finally {
      setLoading(false);
    }
  };

  const copyFull = async () => {
    if (!summary) return;
    try {
      await navigator.clipboard.writeText(summary.fullText);
      message.success('Discharge summary copied to clipboard');
    } catch {
      message.error('Copy failed — please select manually');
    }
  };

  const printSummary = () => {
    if (!summary) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <html><head><title>Discharge Summary — ${patientName ?? patientId}</title>
      <style>
        body { font-family: Arial, sans-serif; font-size: 13px; margin: 40px; line-height: 1.6; }
        h2 { text-align: center; }
        pre { white-space: pre-wrap; font-family: inherit; }
        .footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 12px; font-size: 11px; color: #666; }
      </style></head>
      <body>
        <h2>Discharge Summary</h2>
        <p><strong>Patient:</strong> ${patientName ?? patientId}</p>
        <pre>${summary.fullText}</pre>
        <div class="footer">Generated by iHIMS AI — ${new Date(summary.generatedAt).toLocaleString()}<br>
        ${summary.disclaimer}</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <Card
      size="small"
      title={
        <Space>
          <RobotOutlined style={{ color: '#13c2c2' }} />
          <span>AI Discharge Summary</span>
          <Tag color="cyan" style={{ marginLeft: 4, fontSize: 11 }}>Claude AI</Tag>
        </Space>
      }
      extra={
        summary && (
          <Space>
            <Button
              size="small"
              icon={view === 'structured' ? <CopyOutlined /> : <MedicineBoxOutlined />}
              onClick={() => setView(v => v === 'structured' ? 'full' : 'structured')}
            >
              {view === 'structured' ? 'Full Text' : 'Structured'}
            </Button>
            <Tooltip title="Copy full text">
              <Button size="small" icon={<CopyOutlined />} onClick={copyFull} />
            </Tooltip>
            <Tooltip title="Print">
              <Button size="small" icon={<PrinterOutlined />} onClick={printSummary} />
            </Tooltip>
            <Button size="small" icon={<ReloadOutlined />} onClick={generate} loading={loading}>
              Regenerate
            </Button>
          </Space>
        )
      }
      style={{ marginTop: 16 }}
    >
      {!summary && !loading && (
        <Space direction="vertical" style={{ width: '100%' }} align="center">
          <MedicineBoxOutlined style={{ fontSize: 32, color: '#bfbfbf' }} />
          <Text type="secondary">
            Generate a discharge summary for{' '}
            {patientName ? <strong>{patientName}</strong> : 'this patient'}'s admission
          </Text>
          <Text type="secondary" style={{ fontSize: 12 }}>
            Includes hospital course, discharge medications, follow-up, and PhilHealth notes
          </Text>
          <Button
            type="primary"
            icon={<RobotOutlined />}
            onClick={generate}
            size="large"
            style={{ background: '#13c2c2', borderColor: '#13c2c2' }}
          >
            Generate Discharge Summary
          </Button>
        </Space>
      )}

      {loading && (
        <div style={{ textAlign: 'center', padding: '32px 0' }}>
          <Spin size="large" />
          <div style={{ marginTop: 12 }}>
            <Text type="secondary">
              Compiling admission data and generating discharge summary…
            </Text>
          </div>
        </div>
      )}

      {error && !loading && (
        <Alert
          type="error"
          showIcon
          message="Generation Failed"
          description={error}
          action={<Button size="small" onClick={generate}>Retry</Button>}
        />
      )}

      {summary && !loading && view === 'structured' && (
        <Space direction="vertical" size={0} style={{ width: '100%' }}>
          <SectionBlock label="Chief Complaint"         content={summary.chiefComplaint} />
          <SectionBlock label="Admission Diagnosis"     content={summary.admissionDiagnosis} />
          <SectionBlock label="Hospital Course"         content={summary.hospitalCourse} />

          {summary.proceduresPerformed.length > 0 && (
            <div style={{ marginBottom: 16 }}>
              <Text strong style={{ fontSize: 13, display: 'block', marginBottom: 4 }}>
                Procedures Performed
              </Text>
              <List
                size="small"
                dataSource={summary.proceduresPerformed}
                renderItem={item => (
                  <List.Item style={{ padding: '3px 0', borderBottom: 'none' }}>
                    <Text style={{ fontSize: 13 }}>• {item}</Text>
                  </List.Item>
                )}
                style={{ padding: '8px 14px', background: '#fafafa', border: '1px solid #e8e8e8', borderRadius: 6 }}
              />
            </div>
          )}

          <SectionBlock label="Discharge Diagnosis"    content={summary.dischargeDiagnosis} />
          <SectionBlock label="Condition at Discharge" content={summary.conditionAtDischarge} />
          <SectionBlock label="Discharge Medications"  content={summary.dischargeMedications} mono />
          <SectionBlock label="Activity Restrictions"  content={summary.activityRestrictions} />
          <SectionBlock label="Dietary Instructions"   content={summary.dietaryInstructions} />
          <SectionBlock label="Follow-up Instructions" content={summary.followUpInstructions} />

          {summary.returnPrecautions.length > 0 && (
            <div style={{ marginBottom: 16 }}>
              <Text strong style={{ fontSize: 13, display: 'block', marginBottom: 4, color: '#cf1322' }}>
                Return to ER if…
              </Text>
              <List
                size="small"
                dataSource={summary.returnPrecautions}
                renderItem={item => (
                  <List.Item style={{ padding: '3px 0', borderBottom: 'none' }}>
                    <Text style={{ fontSize: 13, color: '#cf1322' }}>⚠ {item}</Text>
                  </List.Item>
                )}
                style={{ padding: '8px 14px', background: '#fff2f0', border: '1px solid #ffccc7', borderRadius: 6 }}
              />
            </div>
          )}

          {summary.philhealthNote && (
            <div style={{ marginBottom: 16 }}>
              <Text strong style={{ fontSize: 13, display: 'block', marginBottom: 4 }}>
                PhilHealth / HMO Note
              </Text>
              <Alert
                type="info"
                showIcon
                message={summary.philhealthNote}
                style={{ fontSize: 12 }}
              />
            </div>
          )}

          <Divider style={{ margin: '4px 0 8px' }} />
          <Alert
            type="warning"
            showIcon
            icon={<ExclamationCircleOutlined />}
            message={summary.disclaimer}
            style={{ fontSize: 12 }}
          />
          <Text type="secondary" style={{ fontSize: 11, display: 'block', marginTop: 6 }}>
            Generated: {new Date(summary.generatedAt).toLocaleString()}
          </Text>
        </Space>
      )}

      {summary && !loading && view === 'full' && (
        <Space direction="vertical" style={{ width: '100%' }}>
          <Paragraph
            style={{
              background: '#f6fffe',
              border: '1px solid #87e8de',
              borderRadius: 6,
              padding: '14px 16px',
              whiteSpace: 'pre-wrap',
              fontFamily: 'monospace',
              fontSize: 13,
              marginBottom: 0,
              minHeight: 300,
            }}
          >
            {summary.fullText}
          </Paragraph>
          <Alert
            type="warning"
            showIcon
            icon={<ExclamationCircleOutlined />}
            message={summary.disclaimer}
            style={{ fontSize: 12 }}
          />
          <Text type="secondary" style={{ fontSize: 11 }}>
            Generated: {new Date(summary.generatedAt).toLocaleString()}
          </Text>
        </Space>
      )}
    </Card>
  );
};

export default DischargeSummaryPanel;
