import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const HEADER_COLOR: [number, number, number] = [0, 21, 41]; // #001529
const ACCENT_COLOR: [number, number, number] = [24, 144, 255]; // #1890ff
const LIGHT_GRAY: [number, number, number] = [245, 245, 245];

function addHospitalHeader(doc: jsPDF) {
  doc.setFillColor(...HEADER_COLOR);
  doc.rect(0, 0, 210, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('iHIMS General Hospital', 14, 12);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('intelligent Hospital Information System', 14, 18);
  doc.text('123 Healthcare Ave, Manila, Philippines  |  +63 2 1234 5678  |  info@pibs-hospital.ph', 14, 23);
  doc.setTextColor(0, 0, 0);
}

function addFooter(doc: jsPDF) {
  const pageCount = (doc as jsPDF & { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text('Generated by iHIMS', 105, 295, { align: 'center' });
  }
}

export function exportBillPDF(bill: {
  billNo: string;
  createdAt: string;
  patient: { firstName: string; lastName: string; patientNo: string; dateOfBirth?: string };
  items: Array<{ serviceName: string; quantity: number; unitPrice: number; total: number }>;
  subtotal: number;
  seniorDiscount?: number;
  pwdDiscount?: number;
  philhealthDeduction?: number;
  hmoDeduction?: number;
  totalAmount: number;
  amountPaid: number;
  balance: number;
  status: string;
  payments?: Array<{ method: string; amount: number; paidAt: string }>;
}) {
  const doc = new jsPDF();
  addHospitalHeader(doc);

  // Title
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...ACCENT_COLOR);
  doc.text('BILLING STATEMENT', 105, 38, { align: 'center' });

  // Bill info box
  doc.setFillColor(...LIGHT_GRAY);
  doc.roundedRect(14, 42, 90, 30, 2, 2, 'F');
  doc.roundedRect(110, 42, 86, 30, 2, 2, 'F');

  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  doc.setFont('helvetica', 'normal');
  const formatDate = (d: string) => new Date(d).toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' });

  doc.setFont('helvetica', 'bold');
  doc.text('PATIENT INFORMATION', 18, 49);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(`${bill.patient.lastName}, ${bill.patient.firstName}`, 18, 55);
  doc.setTextColor(80, 80, 80);
  doc.text(`Patient No: ${bill.patient.patientNo}`, 18, 60);
  if (bill.patient.dateOfBirth) doc.text(`DOB: ${formatDate(bill.patient.dateOfBirth)}`, 18, 65);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text('BILLING DETAILS', 114, 49);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(`Bill No: ${bill.billNo}`, 114, 55);
  doc.setTextColor(80, 80, 80);
  doc.text(`Date: ${formatDate(bill.createdAt)}`, 114, 60);

  const statusColor: Record<string, [number, number, number]> = {
    PAID: [82, 196, 26], PARTIAL: [250, 140, 22], FINALIZED: [114, 46, 209], DRAFT: [24, 144, 255], CANCELLED: [255, 77, 79],
  };
  const sc = statusColor[bill.status] || [100, 100, 100];
  doc.setFillColor(...sc);
  doc.setTextColor(255, 255, 255);
  doc.roundedRect(151, 62, 22, 7, 1, 1, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.text(bill.status, 162, 66.5, { align: 'center' });

  // Items table
  doc.setTextColor(0, 0, 0);
  const formatPeso = (n: number) => `PHP ${Number(n).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`;

  autoTable(doc, {
    startY: 78,
    head: [['Service / Item', 'Qty', 'Unit Price', 'Total']],
    body: bill.items.map((it) => [
      it.serviceName,
      it.quantity.toString(),
      formatPeso(it.unitPrice),
      formatPeso(it.total),
    ]),
    headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: LIGHT_GRAY },
    columnStyles: { 0: { cellWidth: 90 }, 1: { halign: 'center' }, 2: { halign: 'right' }, 3: { halign: 'right', fontStyle: 'bold' } },
    styles: { fontSize: 9 },
  });

  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;

  // Summary
  const summaryRows: [string, string][] = [['Subtotal', formatPeso(bill.subtotal)]];
  if (bill.seniorDiscount) summaryRows.push([`Senior Citizen Discount (20%)`, `-${formatPeso(bill.seniorDiscount)}`]);
  if (bill.pwdDiscount) summaryRows.push([`PWD Discount (20%)`, `-${formatPeso(bill.pwdDiscount)}`]);
  if (bill.philhealthDeduction) summaryRows.push([`PhilHealth Deduction`, `-${formatPeso(bill.philhealthDeduction)}`]);
  if (bill.hmoDeduction) summaryRows.push([`HMO Deduction`, `-${formatPeso(bill.hmoDeduction)}`]);
  summaryRows.push(['TOTAL AMOUNT DUE', formatPeso(bill.totalAmount)]);
  summaryRows.push(['Amount Paid', formatPeso(bill.amountPaid)]);
  summaryRows.push(['Balance', formatPeso(bill.balance)]);

  autoTable(doc, {
    startY: finalY,
    body: summaryRows,
    tableWidth: 80,
    margin: { left: 116 },
    styles: { fontSize: 9 },
    bodyStyles: { halign: 'right' },
    columnStyles: {
      0: { halign: 'left', textColor: [80, 80, 80], cellWidth: 50 },
      1: { cellWidth: 30, fontStyle: 'normal' },
    },
    didParseCell: (data) => {
      if (data.row.index === summaryRows.length - 3) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fontSize = 11;
        data.cell.styles.fillColor = ACCENT_COLOR;
        data.cell.styles.textColor = [255, 255, 255];
      }
      if (data.row.index === summaryRows.length - 1) {
        data.cell.styles.textColor = bill.balance <= 0 ? [82, 196, 26] : [255, 77, 79];
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // Payments section
  if (bill.payments && bill.payments.length > 0) {
    const py = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(80, 80, 80);
    doc.text('PAYMENT HISTORY', 14, py);
    autoTable(doc, {
      startY: py + 3,
      head: [['Date', 'Method', 'Amount']],
      body: bill.payments.map((p) => [formatDate(p.paidAt), p.method, formatPeso(p.amount)]),
      headStyles: { fillColor: [80, 80, 80], fontSize: 8 },
      styles: { fontSize: 8 },
      columnStyles: { 2: { halign: 'right' } },
      tableWidth: 90,
    });
  }

  addFooter(doc);
  doc.save(`Bill-${bill.billNo}.pdf`);
}

export function exportDischargePDF(data: {
  admissionNo: string;
  patient: { firstName: string; lastName: string; patientNo: string; dateOfBirth?: string; gender?: string; bloodType?: string };
  room?: { roomNumber: string; roomType?: { name: string } };
  attendingDoctor?: string;
  admittedAt: string;
  dischargedAt: string;
  diagnosis?: string;
  notes?: string;
  dischargeNotes?: string;
  vitals?: Array<{ recordedAt: string; temperature?: number; heartRate?: number; bloodPressureSystolic?: number; bloodPressureDiastolic?: number; oxygenSaturation?: number }>;
}) {
  const doc = new jsPDF();
  addHospitalHeader(doc);

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...ACCENT_COLOR);
  doc.text('DISCHARGE SUMMARY', 105, 38, { align: 'center' });

  const formatDate = (d: string) => new Date(d).toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' });
  const formatDateTime = (d: string) => new Date(d).toLocaleString('en-PH', { dateStyle: 'medium', timeStyle: 'short' });

  const admittedDate = new Date(data.admittedAt);
  const dischargedDate = new Date(data.dischargedAt);
  const lengthOfStay = Math.ceil((dischargedDate.getTime() - admittedDate.getTime()) / (1000 * 60 * 60 * 24));

  // Patient info
  autoTable(doc, {
    startY: 42,
    head: [['PATIENT INFORMATION', '']],
    body: [
      ['Patient Name', `${data.patient.lastName}, ${data.patient.firstName}`],
      ['Patient No.', data.patient.patientNo],
      ['Date of Birth', data.patient.dateOfBirth ? formatDate(data.patient.dateOfBirth) : '—'],
      ['Gender', data.patient.gender || '—'],
      ['Blood Type', data.patient.bloodType?.replace('_', ' ') || '—'],
    ],
    headStyles: { fillColor: HEADER_COLOR, textColor: 255 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50, fillColor: LIGHT_GRAY }, 1: { cellWidth: 140 } },
    styles: { fontSize: 9 },
    tableWidth: 90,
  });

  autoTable(doc, {
    startY: 42,
    head: [['ADMISSION DETAILS', '']],
    body: [
      ['Admission No.', data.admissionNo],
      ['Room / Ward', data.room ? `${data.room.roomNumber} (${data.room.roomType?.name || 'Room'})` : '—'],
      ['Attending Doctor', data.attendingDoctor || '—'],
      ['Admitted', formatDateTime(data.admittedAt)],
      ['Discharged', formatDateTime(data.dischargedAt)],
      ['Length of Stay', `${lengthOfStay} day${lengthOfStay !== 1 ? 's' : ''}`],
    ],
    headStyles: { fillColor: HEADER_COLOR, textColor: 255 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50, fillColor: LIGHT_GRAY }, 1: { cellWidth: 140 } },
    styles: { fontSize: 9 },
    tableWidth: 90,
    margin: { left: 110 },
  });

  const nextY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

  // Diagnosis
  if (data.diagnosis) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(80, 80, 80);
    doc.text('DIAGNOSIS / PRINCIPAL CONDITION', 14, nextY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const splitDiag = doc.splitTextToSize(data.diagnosis, 180);
    doc.text(splitDiag, 14, nextY + 5);
  }

  const diagEnd = nextY + (data.diagnosis ? 10 + (data.diagnosis.length / 80) * 5 : 0) + 6;

  // Discharge notes
  if (data.dischargeNotes || data.notes) {
    const text = data.dischargeNotes || data.notes || '';
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(80, 80, 80);
    doc.text('DISCHARGE INSTRUCTIONS / NOTES', 14, diagEnd);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const split = doc.splitTextToSize(text, 180);
    doc.text(split, 14, diagEnd + 5);
  }

  // Latest vitals
  if (data.vitals && data.vitals.length > 0) {
    const lastVital = data.vitals[0];
    const vitY = diagEnd + 30;
    autoTable(doc, {
      startY: vitY,
      head: [['VITAL SIGNS AT DISCHARGE', 'Value']],
      body: [
        ['Temperature', lastVital.temperature ? `${lastVital.temperature} °C` : '—'],
        ['Heart Rate', lastVital.heartRate ? `${lastVital.heartRate} bpm` : '—'],
        ['Blood Pressure', (lastVital.bloodPressureSystolic && lastVital.bloodPressureDiastolic) ? `${lastVital.bloodPressureSystolic}/${lastVital.bloodPressureDiastolic} mmHg` : '—'],
        ['O₂ Saturation', lastVital.oxygenSaturation ? `${lastVital.oxygenSaturation}%` : '—'],
      ],
      headStyles: { fillColor: HEADER_COLOR, textColor: 255 },
      columnStyles: { 0: { fontStyle: 'bold', fillColor: LIGHT_GRAY, cellWidth: 60 } },
      styles: { fontSize: 9 },
      tableWidth: 100,
    });
  }

  // Signature lines
  const sigY = 255;
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  doc.line(14, sigY, 80, sigY);
  doc.text('Attending Physician Signature', 14, sigY + 5);
  doc.line(110, sigY, 196, sigY);
  doc.text('Patient / Guardian Signature', 110, sigY + 5);

  addFooter(doc);
  doc.save(`Discharge-${data.admissionNo}.pdf`);
}
